name = "Synixe Units"
prefix = "units"
mainprefix = "synixe"

[version]
git_hash = 0

[hemtt.launch]
dlc = ["ws"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "497660133", # CUP Weapons
    "497661914", # CUP Units
    "2869054457", # [WS] Low Visibility Attire
    "2871002081", # MilGP Simpel Edit
]

[files]
include = [
    "abramia_co.paa"
]
