name = "Synixe Units"
prefix = "synixeunits"
mainprefix = "synixe"

[hemtt.release]
folder = "synixe_units"

[version]
git_hash = 0

[hemtt.launch.default]
dlc = ["ws", "rf"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "2369477168", # ADT
    "3033967666", # Theseus Units
    "646999497", # Theseus Services
]

[hemtt.launch.aegis]
extends = "default"
workshop = [
    "2538332070", # Aegis - Development
    "2538339575", # Atlas - Development
    "2538342230", # Opposing Forces - Development
    "2402219547", # Theseus
    "2684335735", # Revolución
]

[hemtt.launch.jca_carrier]
extends = "default"
workshop = [
    "3302425224", # JCA MP5
    "2989752481", # JCA Modular Carrier
]
