name = "Synixe Units"
prefix = "synixeunits"
mainprefix = "synixe"

[hemtt.release]
folder = "synixe_units"

[version]
git_hash = 0

[hemtt.launch.default]
dlc = ["ws", "rf"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "2369477168", # ADT
    "3033967666", # Theseus Units
    "646999497", # Theseus Services
]
