name = "Synixe Units"
prefix = "units"
mainprefix = "synixe"

[hemtt.release]
folder = "synixe_units"

[version]
git_hash = 0

[hemtt.launch]
dlc = ["ws"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "497660133", # CUP Weapons
    "497661914", # CUP Units
    "2869054457", # [WS] Low Visibility Attire
    "2871002081", # MilGP Simpel Edit
    "3033967666", # Theseus Units
    "646999497", # Theseus Services
    "2752324758", # Gorkas 'n' Gear
]

[files]
include = [
    "abramia_co.paa"
]
